# Generated by Django 5.2 on 2025-05-14 09:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Логин')),
                ('first_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Используйте только русские символы.', regex='^[А-Яа-яЁё]+$')], verbose_name='Фамилия')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена')),
                ('email_confirmation_code', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('receive_notifications', models.BooleanField(default=True, verbose_name='Получать уведомления')),
                ('phone_number', models.CharField(max_length=20, null=True, verbose_name='Номер телефона')),
                ('img_banner', models.ImageField(default='../static/img/fon.jpg', null=True, upload_to='banner/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Баннер')),
                ('img', models.ImageField(default='avatar/avatar.jpg', null=True, upload_to='avatar/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])], verbose_name='Аватар')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
