# Generated by Django 5.2 on 2025-05-14 09:48

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
                'permissions': [('can_use_tags', 'Может использовать теги')],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('desc', tinymce.models.HTMLField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='article/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'svg', 'webp'])], verbose_name='Изображение')),
                ('status', models.CharField(choices=[('news', 'Новая'), ('published', 'Опубликовано'), ('canceled', 'Отменена')], default='news', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_article', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('img', models.ImageField(null=True, upload_to='img_news/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'svg', 'webp'])], verbose_name='Изображение')),
                ('img_banner', models.ImageField(default='img_banner/fon.png', null=True, upload_to='img_banner/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'svg', 'webp'])], verbose_name='Изображение баннера')),
                ('desc', tinymce.models.HTMLField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='TagsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.article', verbose_name='Статьи')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.news', verbose_name='Новости')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.tags', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Тег новости',
                'verbose_name_plural': 'Теги новости',
                'db_table': 'tags_news',
                'permissions': [('can_add_tags', 'Может добавлять теги к новостям')],
            },
        ),
    ]
